resolver: lts-9.14

packages:
- 'anychem2dock'
- 'vina-utils'
- 'rescore-vina'

extra-deps: []

# Extra package databases containing global packages
# FIXME: use it.
extra-package-dbs: []

ghc-options:
  'vina-utils': -O -Wall -Werror
  'anychem2dock': -O -Wall -Werror
  'rescore-vina': -O -Wall -Werror -Wno-orphans
